const fs = require('fs');
const path = 'd:/Hub/.kiro/specs/hub-art-standardization/design.md';
const content = [];
content.push('# Design Document -- hub-art-standardization');
content.push('');
content.push('## Overview');
content.push('');
content.push('Esta feature realiza a padronizacao e correcoes tecnicas do monorepo **hub-art**. O escopo e cirurgico: renomear pacotes de `hub-musico` para `hub-art`, atualizar documentacao, separar variaveis de ambiente, ajustar rate limiting por rota, corrigir documentacao de seguranca sobre `artist_id`, migrar verificacao de sessao no frontend para a API Fastify, auditar endpoints protegidos, implementar PATCH/DELETE de projetos, adicionar scripts de validacao e atualizar tipos compartilhados.');
content.push('');
content.push('**Restricoes arquiteturais inviolaveis:**');
content.push('- `apps/web` e exclusivamente UI -- nenhuma logica de negocio');
content.push('- `apps/api` (Fastify + Prisma + Zod) e o unico servidor de negocio');
content.push('- `artist_id` SEMPRE do banco via Prisma, nunca do token JWT ou do cliente');
content.push('- Nao remover Fastify, Prisma ou Zod');
content.push('- Mudancas sao cirurgicas -- sem refatoracao de arquitetura');
content.push('');
content.push('**Fase de migracao atual:** Fase 1 (convivencia) -- auth migrado para Fastify, dashboard ainda usa Route Handlers locais para endpoints nao migrados.');
content.push('');
content.push('---');
fs.writeFileSync(path, content.join('\n'), 'utf8');
console.log('Part 1 written: ' + content.length + ' lines');
