import type { Musica, Projeto, Servico, Depoimento } from '@/types'

export const MUSICAS: Musica[] = [
  {
    id: 0,
    title: 'Teste de Áudio Real',
    genre: 'demo',
    genreLabel: 'Demo',
    duration: '0:27',
    key: '—',
    src: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3',
  },
  { id: 1, title: 'Chuva de Inverno', genre: 'piano', genreLabel: 'Piano Solo',  duration: '3:42', key: 'Dm',  src: null },
  { id: 2, title: 'Tarde no Café',    genre: 'jazz',  genreLabel: 'Jazz',         duration: '4:15', key: 'F#m', src: null },
  { id: 3, title: 'Horizonte Aberto', genre: 'ambient', genreLabel: 'Ambient',   duration: '6:08', key: 'Am',  src: null },
  { id: 4, title: 'Prelúdio em G',    genre: 'orquestral', genreLabel: 'Orquestral', duration: '5:30', key: 'G', src: null },
  { id: 5, title: 'Memória Viva',     genre: 'piano', genreLabel: 'Piano Solo',  duration: '4:55', key: 'Cm',  src: null },
  { id: 6, title: 'Noite de Bossa',   genre: 'jazz',  genreLabel: 'Jazz',         duration: '3:58', key: 'Bb',  src: null },
  { id: 7, title: 'Carlos Resende — Álbum Completo', genre: 'jazz', genreLabel: 'Jazz', duration: '—', key: '—', src: null },
  { id: 8, title: 'FUGERE — Álbum Completo', genre: 'rock', genreLabel: 'Rock / Punk', duration: '—', key: '—', src: null },
]

export const PROJETOS: Projeto[] = [
  {
    id: 'fugere',
    title: 'FUGERE',
    description: 'Álbum completo com participação na bateria, disponível no Spotify.',
    year: 'Spotify',
    platform: 'spotify',
    tags: ['Rock / Punk', '▶ Ouvir'],
    href: 'https://open.spotify.com/album/6C2q8Bone8s7KbexQXNeKo?si=CitWia4vTYq2Kk_avtiVgw',
    thumbnailUrl: null,
    spotifyId: '6C2q8Bone8s7KbexQXNeKo',
    featured: true,
    backgroundStyle: 'linear-gradient(135deg, #3a1f5a, #5a2d7a)',
  },
  {
    id: 'acoustic',
    title: "Acoustic 'n Roll",
    description: 'DVD ao vivo com gravação de bateria e performance completa ao lado da banda.',
    year: 'YouTube',
    platform: 'youtube',
    tags: ['Rock', 'DVD ao Vivo', '▶ Assistir'],
    href: 'https://youtu.be/a7VedAE2Qdo?si=ebXjIqB2TeLF9Gk-',
    thumbnailUrl: 'https://img.youtube.com/vi/a7VedAE2Qdo/sddefault.jpg',
    spotifyId: null,
    featured: false,
    backgroundStyle: 'linear-gradient(135deg, #2d2b6b, #4a3f8a)',
    backgroundPosition: 'center 20%',
    backgroundSize: '110%',
  },
  {
    id: 'rodolfo',
    title: 'Rodolfo Lamarca',
    description: 'Participação em DVD com gravação de bateria e arranjos percussivos.',
    year: 'YouTube',
    platform: 'youtube',
    tags: ['DVD', '▶ Assistir'],
    href: 'https://youtu.be/HmBw1-Pu9YQ?si=xKLSbOg6cm4pYsXW',
    thumbnailUrl: 'https://img.youtube.com/vi/HmBw1-Pu9YQ/sddefault.jpg',
    spotifyId: null,
    featured: false,
    backgroundStyle: 'linear-gradient(135deg, #1e2a4a, #2a3d6b)',
  },
  {
    id: 'carlos',
    title: 'Carlos Resende',
    description: 'Álbum completo com participação na bateria, disponível no Spotify.',
    year: 'Spotify',
    platform: 'spotify',
    tags: ['Álbum', '▶ Ouvir'],
    href: 'https://open.spotify.com/album/5UcgfSjEfguojQpGT0Tlo3?si=GuqmRr0wTNCEwXU5fNo4lg',
    thumbnailUrl: null,
    spotifyId: '5UcgfSjEfguojQpGT0Tlo3',
    featured: false,
    backgroundStyle: 'linear-gradient(135deg, #2b1f4a, #3d2a6b)',
  },
  {
    id: 'silva',
    title: 'Silva Soul',
    description: 'Clipe oficial com performance de bateria e produção musical.',
    year: 'YouTube',
    platform: 'youtube',
    tags: ['Soul', 'Clipe', '▶ Assistir'],
    href: 'https://youtu.be/ohCgCqx6Xn0?si=yeugaTjIawUI3VRM',
    thumbnailUrl: 'https://img.youtube.com/vi/ohCgCqx6Xn0/sddefault.jpg',
    spotifyId: null,
    featured: false,
    backgroundStyle: 'linear-gradient(135deg, #1a2550, #2a3570)',
  },
]

export const SERVICOS: Servico[] = [
  {
    id: 'gravacao',
    icon: 'drum',
    title: 'Bateria para Gravação',
    description: 'Gravação profissional de bateria para álbuns, EPs, clipes e DVDs. Versatilidade em rock, MPB, samba, jazz, pop e soul.',
    items: ['Gravação de alta qualidade', 'Múltiplos estilos', 'Entrega em stems'],
    price: 'Consulte o valor',
    highlight: false,
  },
  {
    id: 'shows',
    icon: 'mic',
    title: 'Shows & Performances',
    description: 'Baterista profissional para shows, eventos e apresentações ao vivo com bandas e artistas.',
    items: ['Shows ao vivo', 'Ensaios incluídos', 'Atuação nacional'],
    price: 'Consulte o valor',
    highlight: true,
  },
  {
    id: 'aulas',
    icon: 'music',
    title: 'Aulas de Bateria & Violão',
    description: 'Educação musical presencial em Juiz de Fora. Aulas para iniciantes e intermediários com método personalizado.',
    items: ['Aulas presenciais', 'Bateria e violão', 'Todos os níveis'],
    price: 'Consulte o valor',
    highlight: false,
  },
  {
    id: 'composicao',
    icon: 'compose',
    title: 'Composição & Arranjo',
    description: 'Criação e arranjo musical para projetos autorais, com formação pela Bituca e orientação de Ian Guest.',
    items: ['Composição original', 'Arranjo completo', 'Vários estilos'],
    price: 'Consulte o valor',
    highlight: false,
  },
]

export const DEPOIMENTOS: Depoimento[] = [
  {
    id: 'rodolfo',
    text: '"O Max tem um groove incrível e uma sensibilidade musical rara. A gravação ficou exatamente como precisávamos. Profissional do início ao fim."',
    author: 'Rodolfo Lamarca',
    role: 'Artista Musical',
    initials: 'RL',
    gradient: 'linear-gradient(135deg, #6c63ff, #e040fb)',
  },
  {
    id: 'carlos',
    text: '"Versatilidade e técnica impecáveis. O Max entende o que a música precisa e entrega com precisão e energia em cada performance ao vivo."',
    author: 'Carlos Resende',
    role: 'Músico & Compositor',
    initials: 'CR',
    gradient: 'linear-gradient(135deg, #00c9ff, #92fe9d)',
  },
  {
    id: 'silva',
    text: '"Trabalhar com o Max foi uma experiência incrível. Ele transita entre estilos com muita naturalidade e eleva qualquer projeto a outro nível."',
    author: 'Silva Soul',
    role: 'Artista Musical',
    initials: 'SS',
    gradient: 'linear-gradient(135deg, #f7971e, #ffd200)',
  },
]
